In [75]:
import pickle
import numpy as np

In [76]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [77]:
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([1, 'female', 38.0, 1, 0, 71.2833, 'C'],dtype=object).reshape(1,7)

In [78]:
test_input

array([[1, 'female', 38.0, 1, 0, 71.2833, 'C']], dtype=object)

In [79]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\msi_katana_2\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [80]:
test_input_sex

array([[1., 0.]])

In [81]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [82]:
test_input_embarked

array([[1., 0., 0.]])

In [83]:
test_input_age = test_input[:,2].reshape(1,1)

In [84]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [85]:
test_input_transformed.shape

(1, 10)

In [86]:
# clf.predict(test_input_transformed)

In [87]:
predictions = clf.predict(test_input_transformed)
interpret_predictions(predictions)

def interpret_predictions(predictions):
    for value in predictions:
        if value == 0:
            print("Not Served")
        elif value == 1:
            print("Served")

Served
